### ISSUE TITLE
[Bug] Board crashes when loading captive portal

### ISSUE THREAD

**Issue by redmushie** [OpenShock/Firmware#80]
### Pre-submission checklist

- [X] I checked that no other Bug Report describing my problem exists.
- [X] I am running the latest stable or prerelease firmware.
- [X] My board is on the [list of maintained boards](https://wiki.openshock.org/hardware/boards/#fully-maintained).
- [X] I accept that this issue may be closed if any of the above are found to be untrue.

### Board

Pishock 2023

### Firmware version

1.0.0-rc.2

### Flashing method

I used `esptool write_flash 0x0 <image>`

### Describe what happened as precisely as possible.

When connecting to the captive wifi network and trying to load the captive portal, the board crashes, and the page doesn't finish loading:

After 1 attempt:
![Screenshot_2023-10-31-07-49-54-66_3aea4af51f236e4932235fdada7d1643](https://github.com/OpenShock/Firmware/assets/82113471/b080f255-63a9-42d9-b71d-b57f5516df02)

Then, reconnecting to the wifi network (since it crashed), trying to load it again:
![Screenshot_2023-10-31-07-51-14-51_3aea4af51f236e4932235fdada7d1643](https://github.com/OpenShock/Firmware/assets/82113471/754535d9-8d45-4b67-9c72-5718573f0152)

The board crashes again.

Serial monitor logs:

![image](https://github.com/OpenShock/Firmware/assets/82113471/ab9baeed-84f8-491b-ae2a-2f1d0e0fc567)

### Describe what you expected to happen instead.

Captive portal should load without the board crashing and the wifi connection dropping as a result.

### In as much detail as possible, describe the exact steps you took to make the problem appear.

1. Connect to OpenShock wifi network
2. Visit http://10.10.10.10/
3. (The board crashes while the page is loading)

**Comment by LucHeart** [comment]
Caused by the icon font being too large, CI seems to not strip the icon font used. Works with local build cause the stripping works there.

**Comment by redmushie** [comment]
Interesting. I could probably fix this myself then.

**Comment by hhvrc** [comment]
@LucHeart @redmushie This should be fixed with the latest PR merge

**Comment by redmushie** [comment]
@hhvrc Bet, I'll test it right now

**Comment by redmushie** [comment]
Nope, still happens :(

![image](https://github.com/OpenShock/Firmware/assets/82113471/88c2c0d1-a824-412d-bee0-82e447233530)

![image](https://github.com/OpenShock/Firmware/assets/82113471/ad3ef4ee-0db7-4883-aa72-423cd0d0966e)

**Comment by LucHeart** [comment]
can easily verify by looking at build artifacts, captive portal, icon font should not be 130kb

**Comment by LucHeart** [comment]
*150Kb even

![image](https://github.com/OpenShock/Firmware/assets/26150814/2f8bddab-cbf9-4631-b8b9-ff0dc787d6cb)

**Comment by redmushie** [comment]
@LucHeart That doesn't hold up -- the `captive-portal` artifact is produced by the `build-captive-portal` CI step, which is prior to the optimization done by the `build-filesystem` step.

**Comment by redmushie** [comment]
Did a quick test:

![image](https://github.com/OpenShock/Firmware/assets/82113471/062786a0-f541-4b31-8ef4-74b3707dd2a5)

**Comment by redmushie** [comment]
I think it's most likely a js file that's largest.

Some more logging statements:
![image](https://github.com/OpenShock/Firmware/assets/82113471/7c40e23a-5918-4f9e-a1c7-900253eb28d6)

Regardless, is \[a large file\] really the problem that we need to fix? There should be plenty other ways to approach this problem.

- Find a way to give the ESP some breathing room between serving a ton of assets
- Increase WDT timeout duration if possible
- Disable WDT timeout (oof)
- ...

**Comment by hhvrc** [comment]
@LucHeart @redmushie This is tested to be a issue due to voltage drop when high current is pulled causing the board to crash and reboot

**Comment by LucHeart** [comment]
note: it does not report a brownout...

**Comment by hhvrc** [comment]
That might be the case, but changing the power supply source significally decreases the likelyhood of a crash occuring, this has been tested on 3 seperate units.

I might be wrong in this being purely due to current draw, but a better power supply is tested to improve the reliability by a decent amount.

**Comment by LucHeart** [comment]
Still happens to me on a charger...

**Comment by hhvrc** [comment]
This seems like a hard problem to fix...
What I can do is to manually implement the Stream that streams the file from FS to http and trigger the WDT_RESET from there, this would keep it from crashing.
Temporary fix but should work.
So I read 4kb from file, trigger WDT_RESET, write to http stream, WDT_RESET, repeat...
